### ISSUE TITLE
Streamlining code

### ISSUE THREAD

**Issue by slvstr1** [ECON3/dAuction2_interactive3#28]
We should sit together and look what happens in the code. I somehow suspect some things are calculated double: on the server side and on the front-end site.

**Comment by janvavra** [comment]
Yes, I have time:
Monday: from 12:00
Tuesday: to 14:00
Wendesday: all day

**Comment by slvstr1** [comment]
How about Tuesday at 10:00. I have till about 11:30

**Comment by janvavra** [comment]
Ok, VSE at your office?

**Comment by slvstr1** [comment]
Yes


Doc. Silvester Van Koten <https://sites.google.com/site/slvstrnl/Home>,
Ph.D., +420 776 125 053
*Energy Economics and Experimental Economics*
Associate Professor (Docent) and Deputy Department Head at the University
of Economics in Prague (VŠE <http://www.vse.cz/english/>) and Visiting
Professor at the New Economic School in Moscow (NES
<http://www.nes.ru/en/home/?lang=en>) and CERGE-EI in Prague, Latest publ:
EER <http://www.sciencedirect.com/science/article/pii/S0014292113001220>.

**Comment by janvavra** [comment]
Ok. See you!


---------- Původní zpráva ----------

Od: slvstr1 <notifications@github.com>

Komu: ECON3/dAuction2_interactive3 <dAuction2_interactive3@noreply.github.
com>

Datum: 2. 4. 2016 18:53:55

Předmět: Re: [ECON3/dAuction2_interactive3] Streamlining code (#28)


"
Yes





Doc. Silvester Van Koten <https://sites.google.com/site/slvstrnl/Home>,

Ph.D., +420 776 125 053

*Energy Economics and Experimental Economics*

Associate Professor (Docent) and Deputy Department Head at the University

of Economics in Prague (VŠE <http://www.vse.cz/english/>) and Visiting

Professor at the New Economic School in Moscow (NES

<http://www.nes.ru/en/home/?lang=en>) and CERGE-EI in Prague, Latest publ:

EER <http://www.sciencedirect.com/science/article/pii/S0014292113001220>.



On Sat, Apr 2, 2016 at 6:52 PM, janvavra <notifications@github.com> wrote:



> Ok, VSE at your office?

>

> —

> You are receiving this because you were assigned.

> Reply to this email directly or view it on GitHub

> <https://github.com/ECON3/dAuction2_interactive3/issues/28#issuecomment-
204756594>

>


—

You are receiving this because you were assigned.

Reply to this email directly or view it on GitHub
(https://github.com/ECON3/dAuction2_interactive3/issues/28#issuecomment-204756651)






"=
